site_name: Duon Log
copyright: © 2023 ebene fünf GmbH
nav:
  - index.md
theme:
    name: duon
repo_url: https://github.com/duon/log
extra:
  project: Log
plugins:
  - search
  - macros:
      module_name: docs/main